### PR TITLE
Adding more refresh views to stats views

### PR DESCRIPTION
**Pull request by begrossi**

### CODE REVIEW

**Comment by sushant12** [comment]
Can you please tell me what is refresh views ?

**Comment by adrianob** [comment]
@sushant12 take a look at the documentation for postgres materialized views. We use them for slow queries that don't need to be updated so often.

**Comment by adrianob** [comment]
@sushant12 take a look at the documentation for postgres materialized views. We use them for slow queries that don't need to be updated so often.

**Comment by sushant12** [comment]
Gotcha @adrianob . Thanks

**Pull request merged**
