### PR TITLE
Adds docker for development

### PR DESCRIPTION
**Pull request by kurenn**
### What does this PR do?

* Adds `docker-compose.yml` to run the project
* Locks some gems to prevent new versions to break the app
* Adds `Dockerfile` to create app image
* Add a `HOW-TO` plug & play with docker
* Add test container
* Solves #889

### CODE REVIEW

**Comment by devton** [comment]
Hey @kurenn, thanks by starting the docker implementation o/

Jest need to you look these things:

Specs are failing I think that is because the db/schema.rb file commited we don't use this file on 
repo an .gitignore should be solve this.

About the gems version, you get some error?

**Comment by kurenn** [comment]
@devton I can ignore the schema.rb file, no problem, it is not working anyways.

About the gem version, just to make sure when someone new downloads the project and run the bundle command, does not install a version, in this case devise, that make the app break....

It happened to me, you have any suggestion?

**Comment by devton** [comment]
@kurenn nice, 
about the gems its ok set the versions.

**Comment by devton** [comment]
@kurenn auto_html upgraded gem is failing on specs

**Comment by kurenn** [comment]
There is still one issue pending, @devton do you have any idea on this?

**Comment by kurenn** [comment]
I still have to add a container to run the tests, let me update the pull request with that

**Comment by kurenn** [comment]
This is now ready to merge!

**Comment by devton** [comment]
@kurenn thanks! sorry about delay busy busy week :)

I'll fix the conflicts and merge.

o/

**Comment by kurenn** [comment]
Sweet! can't wait!

**Pull request merged**
