### PR TITLE
Allows category button to link to external page [#140208547]

### PR DESCRIPTION
**Pull request by vicnicius**
@thiagocatarse to create an external link for an specific category just add it's id and link to the explore_categories translation key.

### CODE REVIEW

**Comment by thiagocatarse** [comment]
perfect @vicnicius ! thanks!

**Comment by thiagocatarse** [comment]
Should I do anything about this PR @vicnicius ? The guys will take care of it right?

**Comment by vicnicius** [comment]
@thiagocatarse Yes, they will. It was just so you could see how we are going to do this.

**Comment by thiagocatarse** [comment]
cool!

**Pull request merged**
